[package]
name = "http-rust-server"
version = "0.1.0"
authors = ["Zen <true.grenight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
